# Generated by Django 4.1.3 on 2022-11-04 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('genre', models.CharField(max_length=255, verbose_name='genre')),
                ('author', models.CharField(max_length=255, verbose_name='author')),
                ('rate', models.FloatField(verbose_name='rate')),
                ('date_publish', models.DateTimeField(auto_now_add=True, verbose_name='date publish')),
                ('description', models.TextField(verbose_name='description')),
                ('comment', models.TextField(verbose_name='comment')),
            ],
            options={
                'verbose_name': 'book',
                'verbose_name_plural': 'books',
            },
        ),
    ]
