# Generated by Django 4.1.3 on 2022-11-04 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='comment',
            field=models.TextField(null=True, verbose_name='comment'),
        ),
        migrations.AlterField(
            model_name='book',
            name='rate',
            field=models.FloatField(null=True, verbose_name='rate'),
        ),
    ]
